In [1]:
# Importing librabry in our workplace
import numpy as np

In [2]:
myarray = np.array([1,2,3,4,5])

In [3]:
myarray

array([1, 2, 3, 4, 5])

In [4]:
print(np.__version__)

2.1.3


In [5]:
type(myarray)

numpy.ndarray

In [6]:
tuple_array = np.array((1,2,3,4))
tuple_array
type(tuple_array)

numpy.ndarray

In [7]:
list_array = np.array([1,2,3,4,5])
list_array
type(list_array)

numpy.ndarray

In [8]:
set_array = np.array({200,100,500,1,2,3,4,4})
set_array

array({1, 2, 3, 100, 4, 500, 200}, dtype=object)

In [9]:
#0-D array
zero_array = np.array(2)
zero_array

array(2)

In [10]:
# 1-D array
one_array = np.array([1,2,3,4,5,6,7])
one_array

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
# 2-D array
two_array = np.array([[1,2,3,4,5], [10,20,30,40,50]])
two_array

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [12]:
# 3-D array 
three_array = np.array([[[1,2,3,4],[34,54,66,78]],[[34,56,88,89],[56,76,78,88]]])
three_array1 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(three_array)
print("______________________________")
print(three_array1)

[[[ 1  2  3  4]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]]]
______________________________
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
print(np.ndim(three_array))

3


In [14]:
print(np.ndim(two_array))

2


In [15]:
print(np.ndim(one_array))

1


In [16]:
print(np.ndim(zero_array))

0


In [17]:
arr = np.array([1,2,3,4,5,6],ndmin = 5)

In [18]:
print(arr)

[[[[[1 2 3 4 5 6]]]]]


In [19]:
print(two_array)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [20]:
print(two_array[1,4])

50


In [21]:
print(three_array)

[[[ 1  2  3  4]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]]]


In [22]:
print(three_array[0,0,1])

2


In [23]:
#SLICING 

In [24]:
print(one_array)

[1 2 3 4 5 6 7]


In [25]:
one_array[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [26]:
print(two_array)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [27]:
two_array[1,4]

np.int64(50)

In [28]:
two_array[1,::-2]

array([50, 30, 10])

In [29]:
three_array

array([[[ 1,  2,  3,  4],
        [34, 54, 66, 78]],

       [[34, 56, 88, 89],
        [56, 76, 78, 88]]])

In [30]:
three_array[1,1,1:3]

array([76, 78])

In [50]:
arr = np.array(['applekeerthi', 'bananahi', 'cherryhellohow are you'])

In [51]:
print(arr.dtype)

<U22


In [94]:
myarray = np.array([1,2,3,4,5,0])
print(myarray)
new_array = myarray.astype(bool)
print(new_array)

[1 2 3 4 5 0]
[ True  True  True  True  True False]


In [95]:
copied_array = myarray.copy()
print(f"Original array: {myarray}")
print("")
print(f"Copied array: {copied_array}")
copied_array[0] = 1000
print(f"Edited Copied Array: {copied_array}")
print(f"Original array remains same : {myarray}")
print("")
view_array = myarray.view()
print(f"View of array: {view_array}")
view_array[0] = 1000
print(f"Edited view Array: {view_array}")
print(f"Original array : {myarray}")

Original array: [1 2 3 4 5 0]

Copied array: [1 2 3 4 5 0]
Edited Copied Array: [1000    2    3    4    5    0]
Original array remains same : [1 2 3 4 5 0]

View of array: [1 2 3 4 5 0]
Edited view Array: [1000    2    3    4    5    0]
Original array : [1000    2    3    4    5    0]


In [96]:
print(view_array.base)

[1000    2    3    4    5    0]


In [97]:
print(copied_array.base)

None


In [98]:
print(two_array)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [101]:
print(two_array.shape)

(2, 5)


In [103]:
print(three_array)

[[[ 1  2  3  4]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]]]


In [109]:
three_array = np.array([[[1,2,3,4],[34,54,66,78]],[[34,56,88,89],[56,76,78,88]]])
print(three_array.shape)

(2, 2, 4)


In [112]:
three_array = np.array([[[1,2,3,4],[34,54,66,78]],[[34,56,88,89],[56,76,78,88]],[[34,56,88,89],[56,76,78,88]]])
print(three_array)
print(three_array.shape)

[[[ 1  2  3  4]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]]

 [[34 56 88 89]
  [56 76 78 88]]]
(3, 2, 4)


In [116]:
three_array = np.array([[[1,2,3,4],[34,54,66,78],[34,54,66,78]],[[34,56,88,89],[56,76,78,88],[34,54,66,78]],[[34,56,88,89],[56,76,78,88],[34,54,66,78]]])
print(three_array)
print(three_array.shape)

[[[ 1  2  3  4]
  [34 54 66 78]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]
  [34 54 66 78]]]
(3, 3, 4)


In [140]:
myarray= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
myarray = myarray.reshape(2,2,5)

In [141]:
myarray

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [143]:
myarray = myarray.reshape(-1)

In [144]:
myarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [168]:
# for i in three_array:
#     for j  in i:
#         for k in j:         This will print every element in the array
#             print(k)

In [169]:
for i in np.nditer(two_array):
    print(i)

1
2
3
4
5
10
20
30
40
50
