In [1]:
# Importing librabry in our workplace
import numpy as np

In [2]:
myarray = np.array([1,2,3,4,5])

In [3]:
myarray

array([1, 2, 3, 4, 5])

In [4]:
print(np.__version__)

2.1.3


In [5]:
type(myarray)

numpy.ndarray

In [6]:
tuple_array = np.array((1,2,3,4))
tuple_array
type(tuple_array)

numpy.ndarray

In [7]:
list_array = np.array([1,2,3,4,5])
list_array
type(list_array)

numpy.ndarray

In [8]:
set_array = np.array({200,100,500,1,2,3,4,4})
set_array

array({1, 2, 3, 100, 4, 500, 200}, dtype=object)

In [9]:
#0-D array
zero_array = np.array(2)
zero_array

array(2)

In [10]:
# 1-D array
one_array = np.array([1,2,3,4,5,6,7])
one_array

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
# 2-D array
two_array = np.array([[1,2,3,4,5], [10,20,30,40,50]])
two_array

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [12]:
# 3-D array 
three_array = np.array([[[1,2,3,4],[34,54,66,78]],[[34,56,88,89],[56,76,78,88]]])
three_array1 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(three_array)
print("______________________________")
print(three_array1)

[[[ 1  2  3  4]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]]]
______________________________
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
print(np.ndim(three_array))
print(np.ndim(two_array))
print(np.ndim(one_array))
print(np.ndim(zero_array))

3
2
1
0


In [14]:
arr = np.array([1,2,3,4,5,6],ndmin = 5)

In [15]:
print(arr)

[[[[[1 2 3 4 5 6]]]]]


In [16]:
print(two_array)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [17]:
print(two_array[1,4])

50


In [18]:
print(three_array)

[[[ 1  2  3  4]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]]]


In [19]:
print(three_array[0,0,1])

2


In [20]:
#SLICING 

In [21]:
print(one_array)

[1 2 3 4 5 6 7]


In [22]:
one_array[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [23]:
print(two_array)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [24]:
print(two_array[1,4])

50


In [25]:
two_array[1,::-2]

array([50, 30, 10])

In [26]:
three_array

array([[[ 1,  2,  3,  4],
        [34, 54, 66, 78]],

       [[34, 56, 88, 89],
        [56, 76, 78, 88]]])

In [27]:
three_array[1,1,1:3]

array([76, 78])

In [28]:
arr = np.array(['applekeerthi', 'bananahi', 'cherryhellohow are you'])

In [29]:
print(arr.dtype)

<U22


In [30]:
myarray = np.array([1,2,3,4,5,0])
print(myarray)
new_array = myarray.astype(bool)
print(new_array)

[1 2 3 4 5 0]
[ True  True  True  True  True False]


In [31]:
# Difference betweeen copy() and view()
# Copy function makes another variable and if any changes done on copied_array will be changed to the original array
# view function makes another variable and if any changes done on viewd_array will not be changed to the original array
copied_array = myarray.copy()
print(f"Original array: {myarray}")
print("")
print(f"Copied array: {copied_array}")
copied_array[0] = 1000
print(f"Edited Copied Array: {copied_array}")
print(f"Original array remains same : {myarray}")
print("")
view_array = myarray.view()
print(f"View of array: {view_array}")
view_array[0] = 1000
print(f"Edited view Array: {view_array}")
print(f"Original array : {myarray}")

Original array: [1 2 3 4 5 0]

Copied array: [1 2 3 4 5 0]
Edited Copied Array: [1000    2    3    4    5    0]
Original array remains same : [1 2 3 4 5 0]

View of array: [1 2 3 4 5 0]
Edited view Array: [1000    2    3    4    5    0]
Original array : [1000    2    3    4    5    0]


In [32]:
print(view_array.base)

[1000    2    3    4    5    0]


In [33]:
print(copied_array.base)

None


In [34]:
print(two_array)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [35]:
print(two_array.shape)

(2, 5)


In [36]:
print(three_array)

[[[ 1  2  3  4]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]]]


In [37]:
three_array = np.array([[[1,2,3,4],[34,54,66,78]],[[34,56,88,89],[56,76,78,88]]])
print(three_array.shape)
print(three_array.ndim)

(2, 2, 4)
3


In [38]:
three_array = np.array([[[1,2,3,4],[34,54,66,78]],[[34,56,88,89],[56,76,78,88]],[[34,56,88,89],[56,76,78,88]]])
print(three_array)
print(three_array.shape)

[[[ 1  2  3  4]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]]

 [[34 56 88 89]
  [56 76 78 88]]]
(3, 2, 4)


In [39]:
three_array = np.array([[[1,2,3,4],[34,54,66,78],[34,54,66,78]],[[34,56,88,89],[56,76,78,88],[34,54,66,78]],[[34,56,88,89],[56,76,78,88],[34,54,66,78]]])
print(three_array)
print(three_array.shape)

[[[ 1  2  3  4]
  [34 54 66 78]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]
  [34 54 66 78]]]
(3, 3, 4)


In [40]:
myarray= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(len(myarray))
myarray = myarray.reshape(2,2,5)

20


In [41]:
myarray

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [42]:
# It will flattens the multi dimentional array into 1D array
myarray = myarray.reshape(-1)

In [43]:
myarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
# for i in three_array:
#     for j  in i:
#         for k in j:         This will print every element in the array
#             print(k)

In [45]:
# This function will access every element inside the array irrespective of the array depth
for i in np.nditer(two_array):
    print(i)

1
2
3
4
5
10
20
30
40
50


In [46]:
print(two_array)
for index,i in np.ndenumerate(two_array):
    print(f"{i} ->  {index} ")

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
1 ->  (0, 0) 
2 ->  (0, 1) 
3 ->  (0, 2) 
4 ->  (0, 3) 
5 ->  (0, 4) 
10 ->  (1, 0) 
20 ->  (1, 1) 
30 ->  (1, 2) 
40 ->  (1, 3) 
50 ->  (1, 4) 


In [47]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([89,99,100])

In [48]:
# cocmbining along columns by default
new_array = np.concatenate((arr1, arr2,arr3))
print(new_array)

[  1   2   3   4   5   6  89  99 100]


In [49]:
# specify axis = 1 to combine along rows
new_array = np.concatenate((arr1, arr2,arr3), axis=0)
print(new_array)

[  1   2   3   4   5   6  89  99 100]


In [50]:
# Combining using stack function
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")
print("Stacked array: ")
stack_array = np.stack((arr1, arr2))
print(stack_array)
concat_array = np.concat((arr1, arr2))
print("Concatenation: ")
print(concat_array)

Array 1: [1 2 3]
Array 2: [4 5 6]
Stacked array: 
[[1 2 3]
 [4 5 6]]
Concatenation: 
[1 2 3 4 5 6]


In [51]:
arr1 = [[1,2,3],[4,5,6]]
arr2 = [[10,11,12],[13,14,15]]
# print(np.vstack((arr1, arr2)))
# print(np.concatenate((arr1, arr2),axis  = 0))
print(np.dstack((arr1,arr2)))
print(np.stack((arr1,arr2),axis=0))

[[[ 1 10]
  [ 2 11]
  [ 3 12]]

 [[ 4 13]
  [ 5 14]
  [ 6 15]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]


In [52]:
new_array = [[1,2,3,4],[5,6,7,8]]
print(new_array)

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [53]:
splitted_array = np.array_split(new_array,2)
print(splitted_array)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [54]:
print(splitted_array[0])

[[1 2 3 4]]


In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [56]:
arr = np.array([1, 2, 4])

print(np.where(arr == 2))

(array([1]),)


In [57]:
arr = np.array([6, 10, 10, 9])

x = np.searchsorted(arr, 10)

print(x)


1


In [58]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [59]:
myarray = np.array([1,2,3,4,5])
boolean_array = np.array([True, False, False, False, True])
new_array = myarray[boolean_array]
print(new_array)

[1 5]


In [60]:
# Applying filter concept based on a condition
raw_array = np.array([1,2,6,56,77,79,74,44,12,0,99,97,57,43,31])
bool_array = []
for element in raw_array:
    if element > 80:
        bool_array.append(True)
    else: 
        bool_array.append(False)
bool_array = np.array(bool_array)
print(bool_array)
print(np.where(bool_array == True))
print(raw_array[bool_array])

[False False False False False False False False False False  True  True
 False False False]
(array([10, 11]),)
[99 97]


In [61]:
# Another way of doing
raw_array = np.array([1,2,6,56,77,79,74,44,12,0,99,97,57,43,31])
bool_array = raw_array > 80
print(bool_array)
print(np.where(bool_array == True))
print(raw_array[bool_array])

[False False False False False False False False False False  True  True
 False False False]
(array([10, 11]),)
[99 97]


In [62]:
# Random Number Generation 
from numpy import random
for x in range(0, 10):
    x = np.random.randint(6)
    print(x * " yethish ")

 yethish  yethish  yethish  yethish 
 yethish  yethish 

 yethish  yethish  yethish  yethish  yethish 
 yethish  yethish  yethish  yethish 

 yethish  yethish  yethish 
 yethish 
 yethish 
 yethish  yethish  yethish  yethish  yethish 


In [63]:
x = random.randint(10,30, size=(3,2))
print(x)

[[24 13]
 [12 28]
 [18 25]]


In [64]:
heights = np.random.normal(170, 10, 10)  # mean=170, std=10
print(heights)

[176.02091779 170.17309229 173.69782947 171.27774403 182.07381052
 190.2188037  196.22981939 161.3513791  154.81361172 181.21767892]


In [65]:
print(min(heights))
print(max(heights))

154.8136117221352
196.22981939439612


In [66]:
x = random.rand(5,2)
print(x)

[[0.53342242 0.80830875]
 [0.21235025 0.69496272]
 [0.56094725 0.85964004]
 [0.72971454 0.96556193]
 [0.49757091 0.25797302]]


In [67]:
x = random.choice([1,2,3,4,5,6,7,8,9])
print(x)

3


In [68]:
print(three_array)
print(three_array.itemsize)
print(two_array)
print(two_array.itemsize)

[[[ 1  2  3  4]
  [34 54 66 78]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]
  [34 54 66 78]]

 [[34 56 88 89]
  [56 76 78 88]
  [34 54 66 78]]]
8
[[ 1  2  3  4  5]
 [10 20 30 40 50]]
8


In [69]:
print(three_array.dtype)
print(three_array.nbytes)
print(three_array.itemsize)
print(three_array.itemsize * three_array.size)

int64
288
8
288


In [70]:
print(three_array.size)
print(two_array.size)

36
10


In [76]:
import numpy as np
ar1 = np.arange(5, 50)
ar1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [81]:
ar2 = np.zeros((2,3))
ar2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [83]:
ar3 = np.ones((2,3))
ar3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [86]:
ar4 = np.linspace(0,1,5)
ar4

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [89]:
ar5 = np.eye(3)
ar5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
ar6 = np.random.rand(2)
ar6

array([0.84580673, 0.24077026])

In [101]:
# Normal distribution of mean = 0 and SD= 1
ar7 = np.random.randn(2)   
ar7

array([ 0.61305277, -1.35578906])

In [102]:
ar8 = np.random.randint(10, 50, size=(2,3))
ar8

array([[16, 32, 38],
       [16, 19, 28]], dtype=int32)

In [105]:
#Inspecting arrays
arr = np.random.randint(1,100, size=(3,4))
print(arr)

print("======================")
print(f"Array shape: {arr.shape}")
print(f"Array dimension: {arr.ndim}")
print(f"Array size: {arr.size}")
print(f"Array Data type: {arr.dtype}")

[[82 24 97 51]
 [48 82 64 53]
 [98 15 64  7]]
Array shape: (3, 4)
Array dimension: 2
Array size: 12
Array Data type: int32


In [107]:
# changing the datatype
arr_float = arr.astype(float)
print(arr_float)
print(f"Data type of the array {arr_float.dtype}")

[[82. 24. 97. 51.]
 [48. 82. 64. 53.]
 [98. 15. 64.  7.]]
Data type of the array float64


In [108]:
# Indexing slicing and boolean masking
a = np.array([1,2,3,4,5])
print(a[3])

4


In [109]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[2,2])

9


In [111]:
print(b[:,0])
print(b[1:,1:])

[1 4 7]
[[5 6]
 [8 9]]


In [114]:
#boolean masking
myarray= np.array([1,2,3,4,5,6,7,8,9])
mask = myarray > 5
print(mask)
print(myarray[mask])

[False False False False False  True  True  True  True]
[6 7 8 9]


In [123]:
#Reshaping and transpose


In [124]:
x = np.arange(12)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [125]:
arr = x.reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [126]:
print(arr.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [127]:
flat = arr.ravel()
print(flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [128]:
#Joining and splitting

In [129]:
a = np.array([1,2,3,5])
b = np.array([11,22,44,55])
c = np.concatenate([a,b])
c

array([ 1,  2,  3,  5, 11, 22, 44, 55])

In [131]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2,3],[4,5,6]])
print(np.vstack([A,B]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [132]:
print(np.hstack([A,B]))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [137]:
x = np.arange(20)
left, right = np.split(x,2)
print(left, "------>",right)

[0 1 2 3 4 5 6 7 8 9] ------> [10 11 12 13 14 15 16 17 18 19]


In [138]:
# Basic Math

In [139]:
x = np.array([1,2,3,4,5])
y = np.array([10,20,30,40,50])

print(x + y)
print(x * y)
print(x / y)
print(x - y)

[11 22 33 44 55]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[ -9 -18 -27 -36 -45]


In [140]:
# Aggregations and stats nd functions

In [142]:
A = np.array([[10,20,30,40],[60,70,80,100]])
print(A)

[[ 10  20  30  40]
 [ 60  70  80 100]]


In [147]:
print(A.sum())
print(A.sum(axis=0))
print(A.sum(axis=1))
print(A.min(), A.max())
print(A.mean())
print(np.median(A))
print(np.std(A))

410
[ 70  90 110 140]
[100 310]
10 100
51.25
50.0
29.341736485763757


In [148]:
# Comparision and Where
arr = np.array([1,2,3,4,5,6,7,8,9])
labels = np.where(arr % 2 ==0, "Even","Odd")
print(labels)

['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd']
